function(enable_doxygen)
    option(ENABLE_DOXYGEN "Enable Doxygen for source builds" OFF)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        if(ENABLE_DOXYGEN)
            set(DOXYGEN_CALLER_GRAPH YES)
            set(DOXYGEN_CALL_GRAPH YES)
            set(DOXYGEN_EXTRACT_ALL YES)
            set(DOXYGEN_JAVADOC_AUTOBRIEF YES)
            set(DOXYGEN_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/docs)
            find_package(Doxygen REQUIRED dot)
            doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR}/src/ ALL
                COMMENT "Generating API documentation with Doxygen...")

        endif()
    endif()
endfunction()